"""add supplement_aliases table for slug-redirect history

Revision ID: 8fc48c056c61
Revises: a75a7b59e9cb
Create Date: 2026-05-01 13:28:32.682201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc48c056c61'
down_revision = 'a75a7b59e9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplement_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplement_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplement_aliases_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplement_aliases_supplement_id'), ['supplement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplement_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplement_aliases_supplement_id'))
        batch_op.drop_index(batch_op.f('ix_supplement_aliases_slug'))

    op.drop_table('supplement_aliases')
    # ### end Alembic commands ###
