"""add image_path, image_source, dsld_id, upc to supplements

Revision ID: 923a3a3f8d1b
Revises: ce5d2f898382
Create Date: 2026-04-30 15:36:47.044465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923a3a3f8d1b'
down_revision = 'ce5d2f898382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_source', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('dsld_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('upc', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_supplements_dsld_id'), ['dsld_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_upc'), ['upc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplements_upc'))
        batch_op.drop_index(batch_op.f('ix_supplements_dsld_id'))
        batch_op.drop_column('upc')
        batch_op.drop_column('dsld_id')
        batch_op.drop_column('image_source')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
