"""initial schema: brands, categories, sources, supplements, ratings

Revision ID: ce5d2f898382
Revises: 
Create Date: 2026-04-30 15:25:18.873759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5d2f898382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating_scale', sa.String(length=60), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_slug'), ['slug'], unique=True)

    op.create_table('supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('serving_size', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('price_range', sa.String(length=4), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("form IN ('Capsule', 'Tablet', 'Softgel', 'Powder', 'Liquid', 'Gummy', 'Drop', 'Other') OR form IS NULL", name='ck_supplement_form'),
    sa.CheckConstraint("price_range IN ('$', '$$', '$$$', '$$$$') OR price_range IS NULL", name='ck_supplement_price_range'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.create_index('ix_supplement_brand_category', ['brand_id', 'category_id'], unique=False)
        batch_op.create_index('ix_supplement_featured_created', ['is_featured', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplements_slug'), ['slug'], unique=True)

    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=False),
    sa.Column('buy_url', sa.String(length=500), nullable=True),
    sa.Column('tested_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_score IS NULL OR max_score > 0', name='ck_rating_max_score_positive'),
    sa.CheckConstraint('score IS NULL OR max_score IS NULL OR score <= max_score', name='ck_rating_score_within_max'),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='ck_rating_score_min'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplement_id', 'source_id', name='uq_supplement_source')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index('ix_rating_source_score', ['source_id', 'score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_source_score')

    op.drop_table('ratings')
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplements_slug'))
        batch_op.drop_index(batch_op.f('ix_supplements_name'))
        batch_op.drop_index(batch_op.f('ix_supplements_is_published'))
        batch_op.drop_index(batch_op.f('ix_supplements_is_featured'))
        batch_op.drop_index(batch_op.f('ix_supplements_category_id'))
        batch_op.drop_index(batch_op.f('ix_supplements_brand_id'))
        batch_op.drop_index('ix_supplement_featured_created')
        batch_op.drop_index('ix_supplement_brand_category')

    op.drop_table('supplements')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_slug'))
        batch_op.drop_index(batch_op.f('ix_sources_is_verified'))

    op.drop_table('sources')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
