"""add amazon_candidates, amazon_searched_at to supplements

Revision ID: d9741c1b50c3
Revises: 0f8f7adc007d
Create Date: 2026-05-04 15:22:39.951708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9741c1b50c3'
down_revision = '0f8f7adc007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amazon_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('amazon_searched_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.drop_column('amazon_searched_at')
        batch_op.drop_column('amazon_candidates')

    # ### end Alembic commands ###
