"""add amazon_url, amazon_asin, amazon_data to supplements

Revision ID: e293c678d9dd
Revises: c1a2b3d4e5f6
Create Date: 2026-05-04 14:03:49.832379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e293c678d9dd'
down_revision = 'c1a2b3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amazon_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('amazon_asin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amazon_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index(batch_op.f('ix_supplements_amazon_asin'), ['amazon_asin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplements_amazon_asin'))
        batch_op.drop_column('amazon_data')
        batch_op.drop_column('amazon_asin')
        batch_op.drop_column('amazon_url')

    # ### end Alembic commands ###
