"""add batch_no, manufacturing_date, expiration_date, tested_by to ratings

Revision ID: f9a991b725a1
Revises: 923a3a3f8d1b
Create Date: 2026-04-30 16:03:27.998374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a991b725a1'
down_revision = '923a3a3f8d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_no', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('manufacturing_date', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('tested_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('tested_by')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('manufacturing_date')
        batch_op.drop_column('batch_no')

    # ### end Alembic commands ###
